### ISSUE TITLE
Test cases failed with EI 6.2.0

### ISSUE THREAD

**Issue by JananiKugaa** [wso2-extensions/esb-connector-salesforcebulk#14]
**Description:**
Failed tests:   

**testCreateJobToUploadBatchFileWithNegativeCase**(org.wso2.carbon.connector.integration.test.salesforcebulk.SalesforceBulkConnectorIntegrationTest): expected:<400> but was:<202>
  **testUploadBatchFileWithMandatoryParameters**(org.wso2.carbon.connector.integration.test.salesforcebulk.SalesforceBulkConnectorIntegrationTest): expected:<201> but was:<202>
  **testUploadBatchFileWithNegativeCase**(org.wso2.carbon.connector.integration.test.salesforcebulk.SalesforceBulkConnectorIntegrationTest): expected:<400> but was:<202>

Tests run: 21, Failures: 3, Errors: 0, Skipped: 0

**Comment by anupama-pathirage** [comment]
Closing as this is old issue which is in EI
